# questions.py
# Contains all quiz questions and the money progression table.

questions_easy = [
    {"question": "Saida mak kapitál ida husi Fransa?", "options": ["A: Paris", "B: Berlin", "C: Madrid", "D: Roma"], "answer": "A"},
    {"question": "Saida mak kapitál ida husi Italia?", "options": ["A: Paris", "B: Berlin", "C: Madrid", "D: Roma"], "answer": "D"},
    {"question": "Saida mak kapitál ida husi Espanha?", "options": ["A: Madrid", "B: Berlin", "C: Paris", "D: Roma"], "answer": "A"},
    {"question": "Anime Naruto mai husi Nasaun ne'ebe?", "options": ["A: India", "B: USA", "C: Japaun", "D: Portugal"], "answer": "C"},
    {"question": "Saida mak fó objetu sira atu halakon ba sentru husi rai?", "options": ["A: Magnetismu", "B: Elektromagnetismu", "C: Gravitasaun", "D: Friksaun"], "answer": "C"},
    {"question": "Saida mak unidade ba korenti eletrisidade?", "options": ["A: Volt", "B: Ohm", "C: Watt", "D: Ampere"], "answer": "D"},
    {"question": "Hira mak valor husi 7+5×2?", "options": ["A: 19", "B: 14", "C: 17", "D: 24"], "answer": "C"},
    {"question": "Saida mak perimetru ida ba quadradu ida ne'ebé iha lado ida 5 cm?", "options": ["A: 10 cm", "B: 15 cm", "C: 20 cm", "D: 25 cm"], "answer": "C"},
    {"question": "Planeta ne'ebé konhese hanesan Planeta Merah?", "options": ["A: Rai", "B: Mars", "C: Fulan", "D: Venus"], "answer": "B"},
    {"question": "Se mak hakerek drama Romeo no Juliet?", "options": ["A: Charles Dickens", "B: William Shakespeare", "C: Leo Tolstoy", "D: Mark Twain"], "answer": "B"},
    {"question": "Saida mak símbolu kimika ba Bee?", "options": ["A: H2O", "B: CO2", "C: O", "D: NaCl"], "answer": "A"},
    {"question": "Gas ne'ebé mak abunda liu iha atmosfera husi rai?", "options": ["A: Oksijéniu", "B: Nitrojéniu", "C: Dióksidu Karbonu", "D: Hidrojéniu"], "answer": "B"},
    {"question": "Se mak Top Skor boot liu ba Real Madrid?", "options": ["A: Raul", "B: Karim Benzema", "C: Alfredo Di Stéfano", "D: Cristiano Ronaldo"], "answer": "D"},
    {"question": "Trofeu Liga dos Campeões hira mak Real Madrid iha 2024?", "options": ["A: 5", "B: 14", "C: 15", "D: 6"], "answer": "C"},
    {"question": "Manan nain husi Champions League tinan 2024 husi Klubu ida ne'ebe?", "options": ["A: Real Madrid", "B: Barcelona", "C: Liverpool", "D: Manchester United"], "answer": "A"},
    {"question": "Manan nain husi Copa La liga tinan 2024 husi Klubu ida ne'ebe?", "options": ["A: Real Madrid", "B: Barcelona", "C: Liverpool", "D: Manchester United"], "answer": "A"},
    {"question": "Se mak Fundador husi Aplikasaun Facebook?", "options": ["A: Bill Gates", "B: Elon Musk", "C: Mark Zuckerberg", "D: Antonio Cabral"], "answer": "C"},
    {"question": "Iha tinan saida maka ema sira tun ba dala uluk iha fulan?", "options": ["A: 1967", "B: 1968", "C: 1969", "D: 1970"], "answer": "C"},
    {"question": "Ruin hira maka iha ema nia isin?", "options": ["A: 205", "B: 206", "C: 207", "D: 208"], "answer": "C"},
    {"question": "Rai-fuik boot liu iha mundu nia naran saida?", "options": ["A: Dezertu Sahara", "B: Dezertu Arábia nian", "C: Dezertu Gobi", "D: Dezertu Antártiku"], "answer": "D"},
    {"question": "Nasaun ida-ne'ebé maka fó prezente Estátua Liberdade nian ba EUA?", "options": ["A: Portugal", "B: Fransa", "C: Brazil", "D: Alemanha"], "answer": "B"},
    {"question": "Gas saida maka ai-horis sira absorve durante fotosínteze?", "options": ["A: Oxigenio", "B: Hidrogenio", "C: Dioxidu Karbonu", "D: Nitrogenio"], "answer": "C"},
    {"question": "Mota saida mak naruk liu iha mundu?", "options": ["A: Mota Amazónia", "B: Mota Nilo", "C: Mota Yangtze", "D: Mota Mississippi"], "answer": "B"},
    {"question": "Iha kontinente hira iha mundu?", "options": ["A: 4", "B: 5", "C: 6", "D: 7"], "answer": "D"},
    {"question": "Tuir Relijiaun Kristiaun Maromak nia ukun fuan iha hira?", "options": ["A: 10", "B: 9", "C: 8", "D: 7"], "answer": "A"},
    {"question": "Tuir Relijiaun Kristiaun Sakaramentu iha hira?", "options": ["A: 10", "B: 9", "C: 8", "D: 7"], "answer": "D"},
    {"question": "Nasaun ne'ebe mak kiik liu iha Mundu basea ba nia Area?", "options": ["A: Fiji", "B: Timor-Leste", "C: Vatikanu", "D: Singapura"], "answer": "C"},
    {"question": "Nasaun ne'ebe mak Boot liu iha Mundu basea ba nia Area?", "options": ["A: EUA", "B: Russia", "C: Brazil", "D: Australia"], "answer": "B"},
    {"question": "Nasaun ida ne'ebe mak iha Ilha barak liu iha Mundu?", "options": ["A: Indonezia", "B: Xina", "C: EUA", "D: suésia"], "answer": "D"},
    {"question": "Nasaun ida ne'ebe mak iha Populasaun barak liu iha Mundu?", "options": ["A: Indonezia", "B: Xina", "C: EUA", "D: India"], "answer": "D"},
    {"question": "Nasaun ida ne'ebe mak iha Populasaun uituan liu iha Mundu?", "options": ["A: Vatikanu", "B: Xina", "C: EUA", "D: India"], "answer": "A"}
]

questions_normal = [
    {"question": "See mak hakerek 'Hamlet'?", "options": ["A: Charles Dickens", "B: J.K. Rowling", "C: William Shakespeare", "D: George Orwell"], "answer": "C"},
    {"question": "Hira mak Divisor Komún Boot-Liu (GCD) husi 24 no 36?", "options": ["A: 8", "B: 6", "C: 12", "D: 18"], "answer": "C"},
    {"question": "Musika Eminem ne'ebé iha letra 'You better lose yourself in the music, the moment, you own it, you better never let it go'?", "options": ["A: Lose Yourself", "B: Stan", "C: Mocking Bird", "D: Without Me"], "answer": "A"},
    {"question": "Album Eminem 'The Marshall Mathers LP' sai iha tinan hira?", "options": ["A: 1999", "B: 2000", "C: 2001", "D: 2002"], "answer": "B"},
    {"question": "See mak Prezidente primeiro ida Timor-Leste depois independénsia iha 2002?", "options": ["A: Taur Matan Ruak", "B: José Ramos-Horta", "C: Francisco Guterres", "D: Xanana Gusmão"], "answer": "D"},
    {"question": "Prezidente Timor oan ne'ebé nain hira hetan Prémio Nobel ba Paz iha 1996 ba esforsu nian atu fó paz iha Timor-Leste?", "options": ["A: Taur Matan Ruak", "B: José Ramos-Horta", "C: Francisco Guterres", "D: Xanana Gusmão"], "answer": "B"},
    {"question": "Saida mak HTTP ne'ebé uza iha teknologia internet nian?", "options": ["A: HyperText Transfer Protocol", "B: HighText Transfer Protocol", "C: HyperText Transmit Protocol", "D: High Transmission Transfer Protocol"], "answer": "A"},
    {"question": "Linguajen programa ida ne'ebé uza liu iha web development no iha naran hanesan kafé?", "options": ["A: Python", "B: C++", "C: Java", "D: Ruby"], "answer": "C"},
    {"question": "See mak konsidera hanesan Papa primeiro ida iha Igreja Katolika?", "options": ["A: Papa João Paulo II", "B: Papa Bento XVI", "C: São Pedro", "D: Papa Francisco"], "answer": "C"},
    {"question": "Saida mak doutrina Transubstansiasaun iha Igreja Katolika nian?", "options": ["A: Kreyensa katak paun no vino sai isin no raan Jesu Kristu", "B: Kreyensa iha susar Jesus", "C: Kreyensa iha Trindade Sagrada", "D: Kreyensa iha moris foun nain"], "answer": "A"},
    {"question": "Poeta ida ne'ebé hakerek 'Two roads diverged in a wood, and I— / I took the one less traveled by'?", "options": ["A: Emily Dickinson", "B: Walt Whitman", "C: Robert Frost", "D: William Wordsworth"], "answer": "C"},
    {"question": "See mak autor poesia 'The Raven', ne'ebé hahú ho liafuan 'Once upon a midnight dreary, while I pondered, weak and weary'?", "options": ["A: John Keats", "B: William Blake", "C: T.S. Eliot", "D: Edgar Allan Poe"], "answer": "D"},
    {"question": "Arku Iris iha kor hira?", "options": ["A: 7", "B: 8", "C: 9", "D: 10"], "answer": "A"},
    {"question": "Saida maka símbolu kímiku ba osan-mean?", "options": ["A: H", "B: O", "C: Au", "D: Na"], "answer": "C"},
    {"question": "Nasaun ida-ne'ebé maka koñesidu nu'udar Rai Loro-matan Sa'e nian?", "options": ["A: Xina", "B: Japaun", "C: Korea", "D: India"], "answer": "B"},
    {"question": "Planeta ida-ne'ebé maka ki'ik liu iha sistema solar?", "options": ["A: Marte", "B: Merkúriu", "C: Jupiter", "D: Saturnus"], "answer": "B"},
    {"question": "Saida maka naran prosesu ne'ebé ai-horis sira halo sira nia ai-han?", "options": ["A: Fermentasaun", "B: Fotosinteze", "C: Dizestaun", "D: Respirasaun"], "answer": "B"},
    {"question": "Saida maka moeda nasionál EUA nian?", "options": ["A: Dollar", "B: Yen", "C: Ringit", "D: Poundsterling"], "answer": "A"},
    {"question": "Foho ne'ebe mak as liu iha Mundu?", "options": ["A: Everest", "B: Ramelau", "C: Matebian", "D: Fuji"], "answer": "A"},
    {"question": "Foho ne'ebe mak as liu iha Timor-Leste?", "options": ["A: Everest", "B: Ramelau", "C: Matebian", "D: Fuji"], "answer": "B"},
    {"question": "Sé maka autór ba Harry Potter iha Filme Harry Potter?", "options": ["A: J.K. Rowling", "B: Roald Dahl", "C: J.R.R. Tolkien", "D: Suzanne Collins"], "answer": "A"},
    {"question": "Saida maka fonte enerjia prinsipál ba moris iha Rai?", "options": ["A: Bee", "B: Anin", "C: Loron Matan", "D: Fulan"], "answer": "C"},
    {"question": "Saida maka naran ba órgaun ne'ebé bomba raan iha ema nia isin?", "options": ["A: Matan", "B: Pulmaun", "C: Fuan", "D: Kakutak"], "answer": "C"},
    {"question": "Nasaun ida-ne'ebé maka famozu ho Moru Bo'ot?", "options": ["A: Xina", "B: Timor-Leste", "C: Korea", "D: Indonezia"], "answer": "A"},
    {"question": "Saida maka pontu fermentu bee nian iha grau Celsius?", "options": ["A: 50°C", "B: 150°C", "C: 200°C", "D: 100°C"], "answer": "D"},
    {"question": "Desportu Nasionál Saida maka Famozu liu iha Kanadá?", "options": ["A: Football", "B: Basketball", "C: Volleyball", "D: Ice Hockey"], "answer": "D"},
    {"question": "Planeta ida-ne'ebe mak Boot liu iha Sistema Solar?", "options": ["A: Merkuriu", "B: Jupiter", "C: Marte", "D: Saturnus"], "answer": "B"},
    {"question": "Prosesu atu konverte vapor bee nian ba líkidu hanaran saida?", "options": ["A: Evaporasaun", "B: Kondensasaun", "C: Presipitasaun", "D: Sublimasaun"], "answer": "B"},
    {"question": "Hexágonu ida iha sorin hira?", "options": ["A: 6", "B: 5", "C: 4", "D: 3"], "answer": "A"},
    {"question": "Saida maka unidade moris nian ne'ebé ki'ik liu?", "options": ["A: Selula", "B: Atomu", "C: Molekula", "D: Orgaun"], "answer": "A"},
]

questions_hard = [
    {"question": "Animal ida ne'ebé mak konsidera ho migrasaun naruk-loos iha mamalia sira hotu-hotu?", "options": ["A: Baleia Gray", "B: Elefante Afrikanu", "C: Bear Polar", "D: Fox Arctic"], "answer": "A"},
    {"question": "See mak lead singer husi Coldplay, banda ne'ebé kanta 'A Sky Full of Stars'?", "options": ["A: Jonny Buckland", "B: Guy Berryman", "C: Will Champion", "D: Chris Martin"], "answer": "D"},
    {"question": "Nasaun ida ne'ebé mak hetan medália ouro barak-liu iha hóki lapangan (field hockey) ba mane sira iha Olímpiku?", "options": ["A: Portugál", "B: Turquia", "C: Paquistán", "D: Índia"], "answer": "D"},
    {"question": "Iha ténis, sá mak termu ne'ebé usa atu hakerek vitória iha major championships (Australian Open, French Open, Wimbledon, no US Open) iha tinan ida?", "options": ["A: Golden Slam", "B: Grand Slam", "C: Career Slam", "D: Calendar Slam"], "answer": "B"},
    {"question": "Instrumentu tradicional Timor oan ne'ebé hanesan flauta no ami usa liu iha música folclóru nian?", "options": ["A: Likurai", "B: Bufalo Horn", "C: Babadok", "D: Fahi Boot"], "answer": "C"},
    {"question": "Dansa tradisionál Timor oan ida ne'ebé ami sempre hala'o iha serimónia sira no simboliza selebrasaun moris, funu, no dame?", "options": ["A: Tebe Dai", "B: Likurai", "C: Funu Rai", "D: Kaibauk"], "answer": "B"},
    {"question": "Saida mak ACID nian iha kontestu tranzasaun base dadus nian (database)?", "options": ["A: Accuracy, Consistency, Isolation, Durability", "B: Atomicity, Consistency, Isolation, Durability", "C: Atomicity, Clarity, Independence, Durability", "D: Access, Control, Integrity, Dependability"], "answer": "B"},
    {"question": "Konsíliu ida iha Igreja Katolika ne'ebé hala'o entre 1545 no 1563 atu kontra Reforma Protestante no reforma práticas Igreja nian mak sá?", "options": ["A: Konsíliu Trent", "B: Konsíliu Primeiru Nicea", "C: Konsíliu Vaticano II", "D: Konsíliu Efésios"], "answer": "A"},
    {"question": "Psikologu ida ne'ebé elabora Hierarki Nesesidade (Hierarchy of Needs), teoria motivasionál iha psikolojia ne'ebé inclui modelu ne'esesidade ema nian iha lima nivel mak see?", "options": ["A: Sigmund Freud", "B: Carl Rogers", "C: Abraham Maslow", "D: B.F. Skinner"], "answer": "C"},
    {"question": "Psikologu sira ne'ebé hakerek Self-Determination Theory, teoria ne'ebé fokus iha motivasaun intrinsika no ekstrínsika no identifika autonomia, kompeténsia, no relasaun hanesan ne'esesidade fundaméntal tolu mak see?", "options": ["A: Albert Bandura", "B: Edward Deci no Richard Ryan", "C: Carl Jung", "D: John Watson"], "answer": "B"}
]

money_steps = {
    1: 100,
    2: 200,
    3: 300,
    4: 400,
    5: 500,
    6: 1000,
    7: 2000,
    8: 3000,
    9: 4000,
    10: 5000,
    11: 10000,
    12: 20000,
    13: 30000,
    14: 40000,
    15: 50000,
    16: 100000,
    17: 200000,
    18: 300000,
    19: 1000000
}